<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Forma.Xaml.Game.MonoGame</AssemblyName>
    <RootNamespace>Forma.Xaml.Game</RootNamespace>
    <UseAppHost>false</UseAppHost>
    <IsPackable>false</IsPackable>
    <Nullable>disable</Nullable>
    <FormaNativeRuntime Condition="'$(FormaNativeRuntime)' == '' And '$(MonoGamePlatform)' == 'Native'">true</FormaNativeRuntime>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="$(MonoGameVersion)" />
    <PackageReference Include="$(MonoGamePackageId)" Version="$(MonoGameVersion)" Condition="'$(MonoGameProjectPath)' == ''" />
    <ProjectReference Include="$(MonoGameProjectPath)" Condition="'$(MonoGameProjectPath)' != ''" />
    <PackageReference Include="MonoGame.Runtime.Linux.Vulkan" Version="$(MonoGameVersion)" Condition="'$(FormaNativeRuntime)' == 'true' And '$(NativeRuntimePath)' == '' And $([MSBuild]::IsOSPlatform('Linux'))" />
    <PackageReference Include="MonoGame.Runtime.Mac.Vulkan" Version="$(MonoGameVersion)" Condition="'$(FormaNativeRuntime)' == 'true' And '$(NativeRuntimePath)' == '' And $([MSBuild]::IsOSPlatform('OSX'))" />
    <ProjectReference Include="../Forma.Xaml.Game/Forma.Xaml.Game.csproj" AdditionalProperties="FormaRuntime=MonoGame" />
    <Compile Include="../Forma.Xaml.Game/Program.cs" Link="Program.cs" />
    <MonoGameContentReference Include="../Forma.Xaml.Game/Content/Content.mgcb" />
    <Content Include="$(NativeRuntimePath)" Link="$([System.IO.Path]::GetFileName('$(NativeRuntimePath)'))" CopyToOutputDirectory="PreserveNewest" Condition="'$(FormaNativeRuntime)' == 'true' And '$(NativeRuntimePath)' != ''" />
  </ItemGroup>

</Project>