FROM mcr.microsoft.com/dotnet/sdk:10.0

RUN apt-get update \
    && apt-get install -y --no-install-recommends clang g++ ninja-build python3 python3-pip zlib1g-dev \
    && python3 -m pip install --break-system-packages meson==1.9.1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /repo